--- 
apiVersion: v1
kind: Pod
metadata: 
  name: container-type-pod
  labels:
    app: container-type-pod
    purpose: container_type_pod
spec:
  initContainers:
    - name: initcon-1
      image: alpine
      command:
        - sleep
        - 1m
    - name: initcon-2
      image: alpine
      command:
        - sleep
        - 1m
  containers:
    - name: webnginx-server
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
