---
apiVersion: v1
kind: Pod
metadata:
  name: user-config-pod
spec:
  containers:
    - name: alpinecontainer1
      image: alpine:latest
      command:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: userconfig-cm
        - secretRef:
            name: userconfig-st
