---
apiVersion: v1
kind: Pod
metadata:
  name: nopdb-mysql-pod
spec:
  containers:
    - name: mysqlc
      image: mysql:8
      envFrom:
        - secretRef:
            name: nopdb-secret
      volumeMounts:
        - name: nopdb-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: nopdb-vol
      persistentVolumeClaim:
        claimName: nopdb-pvc
