---
apiVersion: v1
kind: Pod
metadata:
  name: multicontaoner-pod
spec:
  containers:
    - name: webserver
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
    - name: jenkinsserver
      image: jenkins/jenkins:jdk17
      ports:
        - containerPort: 8080
          protocol: TCP
