---
apiVersion: v1
kind: Service
metadata:
  name: petcommerce-svc
spec:
  type: ClusterIP
  selector:
    app: petcommerce-pod
  ports:
    - name: petcomsvcport
      port: 5000
      targetPort: petcomwebport
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcommerce-deploy
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: petcommerce-pod
  template:
    metadata:
      name: petcommerce-pod
      labels:
        app: petcommerce-pod
    spec:
      containers:
        - name: petcommerce-container
          image: panneercts/nopcommerce:v1.0
          ports:
            - name: petcomwebport
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: petcomwebport
            failureThreshold: 3
            periodSeconds: 3
            successThreshold: 1
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: petcomwebport
            failureThreshold: 3
            periodSeconds: 3
            successThreshold: 1
            initialDelaySeconds: 90
