---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: petnopdb-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petnopdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: petnopdb-sc
  resources:
    requests:
      storage: 2Gi

---
apiVersion:
kind:
metadata:
spec:
