---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdb-deploy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: nginxdb-pod
  template:
    metadata:
      name: nginxdb-pod
      labels:
        app: nginxdb-pod
    spec:
      containers:
        - name: mysqldbc
          image: mysql:8
          envFrom:
            secretRef:
              name: nginxdb-secret
          ports:
            - name: dbport
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: nginxdb-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: nginxdb-vol
          persistentVolumeClaim:
            claimName: nginxdb-pvc
