---
apiVersion: v1
kind: Service
metadata:
  name: nginxapp-svc
spec:
  type: NodePort
  selector:
    app: nginxapp-pod
  ports:
    - name: appsvcport
      targetPort: appwebport
      port: 80
      nodePort: 30002
      protocol: TCP
