---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-ext
spec:
  type: ExternalName
  externalName: qt.learning.com
  selector:
    app: nginx-rs-pod
  ports:
    - name: websvcport
      port: 80
      targetPort: webport
