---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-demo
  labels:
    purpose: NginxServiceDemo
spec:
  type: ClusterIP
  selector: 
    app: nginx-rs-pod
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
