apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: qteks-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 1


### eksctl utils associate-iam-oidc-provider --cluster=qteks-cluster --region us-east-2 --approve