--- 
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: prod
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: nginxweb-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginxweb-pod
    spec:
      containers:
        - name: nginxcustweb
          image: panneercts/nginx-custom:v1.0
          env:
            - name: message
              value: Welcome
            - name: purpose
              value: learning
          ports:
            - name: webport
              containerPort: 80
              protocol: TCP
