---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  namespace: prod
spec: 
  type: NodePort
  selector:
    app: nginxweb-pod
  ports:
    - name: svc-port
      port: 80
      targetPort: webport
      nodePort: 30002
 