---
apiVersion: v1
kind: Pod
metadata:
  name: nopmysql-pod
  labels:
    app: nop-mysql
spec:
  containers:
    - name: nopmysqlc
      image: mysql:8
      envFrom:
        - secretRef:
            name: mysqldb-secret
