---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-demo
  labels:
    description: cronjobdemo    
spec:
  schedule: '*/2 * * * *'  
  jobTemplate:
    metadata:
      labels:
        description: jobdemo
    spec:
      backoffLimit: 3    
      template: 
        metadata:
          name: cronjob-batch-pod
          labels:
            app: cronbatch
        spec:
          restartPolicy: OnFailure
          containers:
            - name: alpinecontainer1
              image: alpine:latest
              command:
                - sleep
                - 2m  
