---
apiVersion: v1
kind: Service
metadata:
  name: nginxdb-svc
spec:
  type: ClusterIP
  selector:
    app: nginxdb-pod
  ports:
    - name: dbsvcport
      targetPort: dbport
      port: 80
      protocol: TCP
