---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: jenkins-web
  ports:
    - name: jenkinssvc-port
      port: 80
      targetPort: webport
      nodePort: 30001
      protocol: TCP